server:
  port: 8021
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: binarfood
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/auth/**
#        - id: binarfood
#          uri: http://localhost:8080
#          predicates:
#            - Path=/api/v1/invoice/**
        - id: invoice
          uri: http://localhost:8091
          predicates:
            - Path=/api/v2/invoice/**
          filters:
            - AuthenticationFilter
        - id: auth
          uri: http://localhost:8022
          predicates:
            - Path=/api/v1/auth/**
        - id: binarfoodchat
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/binarfood-message/**
#        - id: socketio
#          uri: http://localhost:8100
#          predicates:
#            -




